[tool.poetry]
name = "redis-developer"
version = "0.1.0"
description = "A high-level library containing useful Redis abstractions and tools, like an ORM and leaderboard."
authors = ["Andrew Brookins <andrew.brookins@redislabs.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
redis = "^3.5.3"
aioredis = "^2.0.0"
pydantic = "^1.8.2"
click = "^8.0.1"
six = "^1.16.0"
pptree = "^3.1"
types-redis = "^3.5.9"
types-six = "^1.16.1"
python-ulid = "^1.0.3"
python-dotenv = "^0.19.1"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pytest = "^6.2.4"
ipdb = "^0.13.9"
pylint = "^2.11.1"
black = "^21.9b0"
isort = "^5.9.3"
flake8 = "^4.0.1"
bandit = "^1.7.0"
coverage = "^6.0.2"
pytest-cov = "^3.0.0"


[tool.poetry.scripts]
migrate = "redis_developer.orm.cli.migrate:migrate"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
